import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import assert from 'node:assert/strict'

const root = resolve(import.meta.dirname, '..')
const news = readFileSync(resolve(root, 'src/views/tdx/TdxNewsFeed.vue'), 'utf8')
const limitUp = readFileSync(resolve(root, 'src/views/tdx/TdxLimitUpLive.vue'), 'utf8')
const speech = readFileSync(resolve(root, 'src/composables/useSpeech.ts'), 'utf8')
const voice = readFileSync(resolve(root, 'src/views/tdx/TdxNewsVoice.vue'), 'utf8')

assert.match(voice, /useTdxPluginRealtime/, 'voice-only plugin should listen to realtime aggregate news')
assert.match(voice, /useSpeech/, 'voice-only plugin should use the shared speech queue')
assert.match(voice, /getTdxNews\(\{\s*limit:\s*20\s*\}\)/, 'voice-only plugin should load a small initial news snapshot')
assert.match(voice, /handleSpeechToggle/, 'voice-only plugin should expose a user gesture speech toggle')
assert.match(voice, /recentTitle/, 'voice-only plugin should show the latest spoken title')
assert.match(voice, /spokenCount/, 'voice-only plugin should show the spoken count')
assert.doesNotMatch(voice, /v-for="item in items"/, 'voice-only plugin should not render a large news list')

assert.match(news, /import\s*\{\s*computed,\s*onMounted,\s*onUnmounted,\s*ref,\s*watch\s*\}/, 'news feed should watch realtime and unlock state changes')
assert.match(news, /@change="handleSpeechToggle"/, 'news speech switch should unlock through a handler')
assert.doesNotMatch(news, /speakVisibleNews/, 'news feed should not replay existing visible news when opened or enabled')
assert.doesNotMatch(news, /speechUnlocked\.value\)\s*speak/, 'news feed should not speak existing items after initial load')
assert.match(news, /spokenNewsKeys/, 'news feed should keep its own spoken-key guard for realtime items')
assert.match(news, /markKnownNews/, 'news feed should mark the initial snapshot as known before realtime speech starts')
assert.match(news, /newsSpeechText/, 'news feed should build speech text from the aggregate news title')
assert.match(news, /item\.source === '韭研公社'/, 'JYGS study-publish posts should get a shorter new-post speech format')
assert.doesNotMatch(news, /normalizeNewsSpeechContent/, 'aggregate news speech should not read source content')
assert.doesNotMatch(news, /const digest =/, 'aggregate news speech should not append digest content')
assert.match(news, /return title\.slice\(0,\s*120\)/, 'aggregate news speech should only read the title')
assert.doesNotMatch(news, /IMPORTANT_NEWS_THRESHOLD/, 'aggregate voice news should not be blocked by an importance threshold')
assert.match(news, /function shouldSpeakNews\(item: TdxNewsItem\) \{\s*return Boolean\(item\.news_id && item\.title\)\s*\}/, 'aggregate voice news should enqueue every titled item and rely on spoken-key dedupe')
assert.doesNotMatch(news, /newsItems\.filter\(isAggregateNewsItem\)/, 'JYGS latest study-publish posts should still be eligible for new-post speech')
assert.match(news, /watch\(\s*realtimeNewsItems/, 'news feed should enqueue new realtime aggregate news')
assert.match(news, /enqueuePluginSpeech\(newsSpeechText\(item\),\s*key,\s*\{\s*force:\s*true\s*\}\)/, 'news feed speech should use the plugin voice switch instead of global limit-up alert settings')
assert.doesNotMatch(news, /const important = payload\.value\.items\.find/, 'news feed should not only attempt one load-time important item')

assert.doesNotMatch(limitUp, /news-voice-strip/, 'limit-up live plugin should not render an aggregate news voice status strip')
assert.doesNotMatch(limitUp, />\s*聚合快讯语音\s*</, 'limit-up live plugin should not display a verbose aggregate voice title')
assert.doesNotMatch(limitUp, /待开启|已播|等待新快讯|newsVoiceStatusText|newsSpokenCount/, 'limit-up live plugin should not show aggregate voice status text')
assert.match(limitUp, /NEWS_SNAPSHOT_LIMIT = 20/, 'limit-up live plugin should keep the aggregate news snapshot small')
assert.match(limitUp, /getTdxNews\(\{\s*limit:\s*NEWS_SNAPSHOT_LIMIT\s*\}\)/, 'limit-up live plugin should load a small aggregate news snapshot')
assert.match(limitUp, /watch\(\s*realtimeNewsItems/, 'limit-up live plugin should listen to realtime aggregate news')
assert.match(limitUp, /@change="handleSpeechToggle"/, 'limit-up live plugin should use one shared speech switch handler')
assert.doesNotMatch(limitUp, /@change="unlockSpeech"/, 'limit-up live plugin should not expose a separate direct speech switch')
assert.match(limitUp, /hasPrimedLimitUpSpeech/, 'limit-up live plugin should prime status events before speaking')
assert.match(limitUp, /function handleStatusEvents/, 'limit-up live plugin should route status events through a priming guard')
assert.match(limitUp, /rememberExistingEvents\(items\)[\s\S]*hasPrimedLimitUpSpeech = true[\s\S]*return/, 'first status payload should be remembered without sequential speech')

assert.match(speech, /type PluginSpeechOptions/, 'plugin speech should have its own options')
assert.match(speech, /function enqueuePluginSpeech\(text: string,\s*key\?: string,\s*options: PluginSpeechOptions = \{\}\)/, 'plugin speech should accept options')
assert.match(speech, /options\.force \|\| getSpeechEnabled\(\)/, 'forced plugin speech should bypass the original app limit-up alert switch')

console.log('tdx news speech checks passed')
